# Generated by Django 4.2.1 on 2023-05-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productopruebas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopruebas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
