# Generated by Django 4.2.1 on 2023-06-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_donacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='monto_donado',
            new_name='monto_a_donar',
        ),
    ]
