# Generated by Django 4.2.1 on 2023-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_monto_donado_donacion_monto_a_donar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='creado_en',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='modificado_en',
            field=models.DateField(auto_now=True, default='2023-06-25'),
            preserve_default=False,
        ),
    ]
