# Generated by Django 4.2.1 on 2023-05-20 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productoespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado_en',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductoEspecial',
        ),
    ]
