# Generated by Django 4.2.1 on 2023-06-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_marca_alter_producto_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
