# Generated by Django 4.2.1 on 2023-06-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_estadosuscripcion_suscripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoSuscripcion',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='estado',
        ),
    ]
