# Generated by Django 4.2.1 on 2023-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_orden_precio_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descuento_sub',
            field=models.IntegerField(default=0),
        ),
    ]
